'Sitegeist.NeosTemplate.Spectral:Mixin.Peroperty.Text.Plain':
  abstract: true

  properties:
    text:
      ui:
        type: string
        inlineEditable: true
        inline:
          editorOptions:
            placeholder: 'Please insert text here.'
            autoparagraph: false
            linking:
              anchor: true
              title: true
              relNofollow: false
              targetBlank: false
            formatting:
              strong: false
              em: false
              u: false
              sub: false
              sup: false
              del: false
              p: false
              h1: false
              h2: false
              h3: false
              h4: false
              pre: false
              underline: false
              strikethrough: false
              removeFormat: true
              left: false
              right: false
              center: false
              justify: false
              table: false
              ol: false
              ul: false
              a: false
